### ISSUE TITLE
Not compatible with rails 4

### ISSUE THREAD

**Issue by jackregnart** [sakovias/axlsx_styler#1]
Tried installing this earlier, are there actually problems with newer versions of Rails, or is this just a dependency syntax issue?

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    axlsx_styler (>= 0) ruby depends on
      activesupport (~> 3.1) ruby

    rails (= 4.1.4) ruby depends on
      activesupport (4.1.4)
```

**Comment by sakovias** [comment]
Sorry, only tested the gem on a Rails 3 project. Thanks for pointing this out. I think the following line in the gemspec file needs to be changed:

    spec.add_dependency 'activesupport', '~> 3.1'

to

    spec.add_dependency 'activesupport', '>= 3.1'

I can try to make this change later this week, but a PR is welcome too.

**Comment by sakovias** [comment]
@jackregnart, I've made a fix and bumped up the gem's version. Please let me know if you still have issues.
