### ISSUE TITLE
undefined method `styles_applied' for nil:NilClass

### ISSUE THREAD

**Issue by jaronson** [sakovias/axlsx_styler#11]
Only occurring since 0.1.4. It appears that `@workbook` is not defined at the point of calling `apply_styles`. However, `Axlsx::Package` provides a `workbook` method, which returns the workbook.

Replacing `@workbook` with `workbook` corrects the issue. PR forthcoming.

**Comment by sakovias** [comment]
@jaronson Thank you for reporting the issue. This must be a very frustrating bug.

I'm quite convinced your fix https://github.com/sakovias/axlsx_styler/pull/12 should work for everyone, but I'm not being able to reproduce. Here's what I'm doing:

``` ruby
# Gemfile
source 'https://rubygems.org'
gem 'axlsx_styler', '0.1.4'

# test.rb
require 'axlsx_styler'
axlsx = Axlsx::Package.new
axlsx.workbook.add_worksheet do |sheet|
  sheet.add_row ['A1', 'B1']
  sheet.add_style 'A1:B1', b: true
end
axlsx.serialize 'result.xlsx'
```

The command `ruby test.rb` works fine, and the Excel file is produced. I also tried some other approaches to break it. Please let me know how I can reproduce the issue. Would be ideal to add something to the test suite.

**Comment by kiuKisas** [comment]
We've run into the same error when I try to render `_XXX.xlsx.axlsx` partial in my template. I just following the [axlsx-rails doc](https://github.com/straydogstudio/axlsx_rails#partials). It may help to reproduce the bug ;)

**Comment by sakovias** [comment]
Thanks @kiuKisas, will prioritize it then...

**Comment by sakovias** [comment]
Removed the old version from RubyGems and pushed a new one (0.1.5) that includes the fix.
