### ISSUE TITLE
Add all available style options section to readme

### ISSUE THREAD

**Issue by westonganger** [sakovias/axlsx_styler#13]
I think it would be fantastic to have a section in the readme which we can use as reference for all available style options.

For example I just had to look up all of the available border styles in the axlsx documentation which by the way are `:none :thin :medium :dashed :dotted :thick :double :hair :mediumDashed :dashDot :mediumDashDot :dashDotDot :mediumDashDotDot :slantDashDot`

Another example is format instructions for `number_format_code`.

I would be interested in helping compile this list. As an added bonus this would probably drive a lot of axlsx traffic to this useful gem. What do you think about adding this.

**Comment by sakovias** [comment]
Yes, having a nice readme with a list of available options would be great. Thanks for suggesting your help!

While I do believe many users of `axlsx` could have benefited from using this gem, I'd prefer not to confuse people as if what we offer here is the "real thing". `axlsx_styler` is merely a plugin for `axlsx` which is a result of enormous effort from @randym and community.  We don't add any new styles in this gem, so I think it could be more appropriate to improve documentation on `axlsx` and give a reference to the documentation here.

**Comment by westonganger** [comment]
No its merely a styling gem I think thats fairly obvious.

Axlsx's github page is very geared towards the yard documentation. But low level documentation like that is thick and in an easy to read list plus I hate having to do all work to get at the docs. Plus axlsx is relatively stagnant and is going to be much more difficult to get a PR through. 

If we add the list here we can control that it at least gets released then eventually it could be adapted into a PR over on the axlsx repo.

**Comment by sakovias** [comment]
How about putting a PR up for `axlsx` first? The docs can be outside of the main readme (to avoid style conflicts with the existing yard documentation), but linked to the front page. We can then link up the docs to this gem as well. I'm noticing that PRs are being merged in the `axlsx` repo by different people, so there's hope 😃

**Comment by westonganger** [comment]
Alright well I am going to add this info somehow in my gem `spreadsheet_architect` then instead cause I want this information to be accessible for my users in the near future. I can let you know when this is more or less completed and we can think about making that PR.

**Comment by westonganger** [comment]
I have created this document. Would you mind glancing over this and letting me know of any additions you have for this?

Here is the temporary link to the document until its moved to master: https://github.com/westonganger/spreadsheet_architect/blob/develop/docs/axlsx_style_reference.md

Once its in master this will be the link: https://github.com/westonganger/spreadsheet_architect/blob/master/docs/axlsx_style_reference.md

**Comment by sakovias** [comment]
That's great stuff! 👍 

I didn't know so many options are available. Should definitely be merged into `axlsx`!
