### ISSUE TITLE
add_style overwrites all previous styles

### ISSUE THREAD

**Issue by westonganger** [sakovias/axlsx_styler#14]
I had already defined row styles through plain axlsx but I was applying a column style using `add_style` and noticed it was overwriting all previous styles. 

Is there any way we can get it to only add on to the other styles?

**Comment by sakovias** [comment]
Originally, I wasn't going to support this. Let me re-evaluate and see what we can do.

**Comment by sakovias** [comment]
Haven't looked into this, but I think it's not going to be a quick fix. If that could be done without patching `axlsx`, that would be perfect. Feel free to investigate!

**Comment by westonganger** [comment]
Another problem here is when using `add_border` as it removes all styles that were applied to it previously by `axlsx`.

I investigated that method which didn't work out. However I have delved deep into axlsx lately and I think I may have found a way to do this. I would need to patch the `add_style` method of Axlsx::Styles though if that is acceptable.

**Comment by sakovias** [comment]
Sounds good. Is this change required for Spreadsheet Architect or it's more of nice-to-have?

I'm a bit hesitant about a change like this since all styles can be added with `add_style` and there's a big risk of introducing some bugs, while I'm not an active user of this gem. I think this change will need a lot of tests before the release. I'll be away at the end of July, but will be happy to review / contribute in August.

**Comment by westonganger** [comment]
Well for any proper border support and better behaviour of range styles this will be required. 

August is fine though I will try to make a PR before then. Basically I want to add another optional argument to this method which accepts the cells xf object which we can extract existing styles form and merge into the new one being created by this method. So unless that argument is present the functionality will remain the same.

**Comment by westonganger** [comment]
I was able to make this happen over at my fork https://github.com/westonganger/axlsx_styler.

It does monkey patch two method in `Axlsx::Styles` however it only adds an optional argument to each to provide the improved functionality so that the original method behaviour is still maintained. You can see these additional patches in `lib/axlsx_styler.rb`. I think the monkey patches should be moved to seperate file(s) as they are starting to pollute this main file.

Also I had to make changes to the `Axlsx::Workbook#set_style_index` method in `lib/axlsx_styler/axlsx_workbook.rb` to make this work because the original implementation had no regard for styles set by plain axlsx.

I think this is a huge improvement for this library. Let me know your thoughts. I will add tests and make a PR if you are happy with it.

**Comment by westonganger** [comment]
Have you had a chance to look at this yet?

**Comment by sakovias** [comment]
Looks good. Thanks for your work!

There are a couple of things I notice. Most of the tests are failing, producing more styles than expected in the style index. I will need to look more thoroughly to understand the reasons. Obviously, for changes like this it's expected to get broken tests :smile: 

Correct me if I'm wrong, but my second observation is that styles are not getting merged properly when I mix old syntax and that brought over from `axlsx`. Here's an example.

``` ruby
require 'axlsx_styler'

axlsx = Axlsx::Package.new
workbook = axlsx.workbook

bold = workbook.styles.add_style b: true

workbook.add_worksheet do |sheet|
  sheet.add_row ['A1', 'B1'], style: [nil, bold]
  sheet.add_row ['A2', 'B2']
  sheet.add_style 'B1:B2', bg_color: 'ff0000'
end

axlsx.serialize 'test.xlsx'
```

The bold style in cell B1 gets overridden by red background color.

![axlsx-merging-problem](https://cloud.githubusercontent.com/assets/4750367/17501134/1c711cfc-5ddc-11e6-8dc0-9a7b02e7e208.png)

**Comment by westonganger** [comment]
Yes there will be increased styles because in order to "merge" it instead creates a new style object. I changed the implementation of `Axlsx::Workbook#set_style_index`. We should probably ensure we are doing all we can to use less style objects. Now that we are monkey patching `add_styles` we can probably add logic for `style_index` and `raw_style` in this method.

I just made a commit that should fix the styles merging.

**Comment by sakovias** [comment]
I pulled the latest, and it looks like the same manual test above is failing. The cell B1 is not getting bold face.

I also tried another test, where I apply border that covers one of cells with bold face
``` ruby
require 'axlsx_styler'

axlsx = Axlsx::Package.new
workbook = axlsx.workbook

bold = workbook.styles.add_style b: true

workbook.add_worksheet do |sheet|
  sheet.add_row ['A1', 'B1'], style: [nil, bold]
  sheet.add_row ['A2', 'B2']
  sheet.add_border 'A1:B2'
end

axlsx.serialize 'bold_vs_border.xlsx'
```
No luck unfortunately:

![bold_vs_border](https://cloud.githubusercontent.com/assets/4750367/17538643/941f8740-5ea7-11e6-8e5c-55481bb47e71.png)

Ideally these tests should be automated.

As far as the tests go, the number of styles in the index should not change. I'm noticing that on your fork you've disabled style indexing (that guarantees uniqueness of styles)
``` ruby
      def set_style_index(cell)
        self.style_index ||= {}

        index_item = style_index.select { |_, v| v == cell.raw_style }.first
        if index_item
          cell.style = index_item.first # this one
        else
        # ...
```
If a spreadsheet has too many styles, Excel (at least older versions) can crash or perform very poorly. That's the issue I was facing in earlier iterations of the gem where a style was created for almost every cell.

**Comment by westonganger** [comment]
Thanks for the comments and help testing. I will have to revisit this on to get it merging correctly, try to utilize the style_index caching as best possible, and will add some tests to automate this.

**Comment by sakovias** [comment]
Sounds good! I may spend some time over the weekend to understand how it works. One of the options is to put it as a PR (so we can make comments) and iterate on it.

**Comment by sakovias** [comment]
Just checked that when we call
```
workbook.styles.add_style <style hash>
```
the original style hash is broken down into a bunch of objects: border, numeric format, font ID, etc.

Here's an example
``` ruby
bold = wb.styles.add_style b: true
red  = wb.styles.add_style fg_color: 'ff0000'
# => 3
# => 4

wb.styles.cellXfs[bold]
wb.styles.cellXfs[red]
#<Axlsx::Xf:0x000000035f01b0 @borderId=0, @numFmtId=0, @fontId=1, @fillId=0, @applyNumberFormat=false, @applyFill=false, @applyFont=true, @applyBorder=false, @applyAlignment=false, @applyProtection=false>
#<Axlsx::Xf:0x000000035ee1f8 @borderId=0, @numFmtId=0, @fontId=2, @fillId=0, @applyNumberFormat=false, @applyFill=false, @applyFont=true, @applyBorder=false, @applyAlignment=false, @applyProtection=false>

wb.styles.fonts.to_a
# [
#     [0] #<Axlsx::Font:0x000000035f5818 @name="Arial", @sz=11, @family=1>,
#     [1] #<Axlsx::Font:0x000000035f09d0 @name="Arial", @sz=11, @family=1, @b=true>,
#     [2] #<Axlsx::Font:0x000000035eebd0 @name="Arial", @sz=11, @family=1, @color=#<Axlsx::Color:0x000000035ee810 @rgb="FFFF0000">>
# ]
```

If I understand it correctly, you were trying to convert the styles given by Ruby hashes into `Axlsx::Xf` instances, which is one approach that requires manipulating this long list of properties `@borderId`, `@numFmtId`, `@fontId`, `@fillId`... Another approach would be to convert `Axlsx::Xf` back into Ruby hash, to make merging styles similar to merging hashes. I think patching `axlsx` should not be required in either of approaches, as it provides a bunch of getter methods.

Of course, this is doable, but I'm not sure if what you're trying to achieve in `SpreadsheetArchitect` is not entirely possible with what `axlsx_styler` or `axlsx` already provide. A concrete example to demonstrate your pain points is appreciated :)

**Comment by sakovias** [comment]
Actually, there's another solution I can think of.
1) Find out which arguments are passed to `Styles#add_style`, i.e. figure out what the original style Hash is before compilation (e.g. `{ b: true }`)
2) Find which styles cells receive during the `sheet.add_row` operation
3) Merge the obtained styles using `AxlsxStyler::Axlsx::Cell#add_to_raw_style`, which should be a small modification to `axlsx_styler`

**Comment by westonganger** [comment]
Your last solution helped me come up with the proper implementation. I just created a PR for this. Interested to get your feedback.

**Comment by westonganger** [comment]
Now that this is implemented can we get a new release?

**Comment by sakovias** [comment]
Thanks for the reminder @westonganger! I just pushed the gem.

I'm hoping CI pipelines won't get busted :stuck_out_tongue_winking_eye:

**Comment by abdulhanan00** [comment]
```
 italic_style = sheet.styles.add_style(:u => true, :sz => 8, :font_name => "Calibri Light",
         :width => 5, alignment: {:horizontal => :center, :wrap_text => true}, :i => true ) 
         
```
:u => true is not working in my case when I use :u => true as separate its override all other sytle

**Comment by newfylox** [comment]
Having this issue lately, if I use a previous style like this on a row
```ruby
sheet.add_row ["Key 1", '', '', "Value 1"], style: Axlsx::STYLE_THIN_BORDER
```
and then later add another style like this
```ruby
sheet.add_style sheet.rows.last.cells.last.r, { b: true }
```
to make "value 1" bold, it will remove its borders. Any hints?

**Comment by westonganger** [comment]
@newfylox few questions:

1 What versions of caxlsx / axlsx_styler are you using. 
2 Does it work if, you do not use `Axlsx::STYLE_THIN_BORDER` and instead use `{border: {style: :thin, color: '000' }}`
3 Can you confirm that `require 'axlsx_styler'` doesnt change anything.
4 Also you say "lately" was it working for you before at some point? If so any further details?

**Comment by newfylox** [comment]
Great questions @westonganger 
1. `caxlsx-3.1.1` and `axlsx_styler-1.1.0`
1.  using the code below works. I don't know if you had another way to test it (with axlsx_style instead of plain caxlsx)
    ```ruby
    wb = xlsx_package.workbook
    s = wb.styles
    border = s.add_style border: { style: :thin, color: "000000" }
    ...
    sheet.add_row ['1', '2', '3', '4'], style: border
    ...
    ```
1. `require 'axlsx_styler'` doesn't change anything (with or without)
1.  Sorry for the word "lately", I was meaning those days but nothing to do with the past.

**Comment by newfylox** [comment]
While my previous answer says that the code work, it causes another problem.
Using plain **caxlsx** style with **axlsx_styler** `centered` style removes my default font to "Arial"
```ruby
border = s.add_style border: { style: :thin, color: "000000" } # plain caxlsx
sheet.add_row ['1', '2', '3', '4'], style: border # plain caxlsx
sheet.add_style sheet.rows.last.cells.last.r, centerer # axlsx_style
```

**Comment by westonganger** [comment]
Instead of using `wb.styles.add_style` try just adding your styles directly to `add_row`

```ruby
default_styles = {border: {style: :thin, color: "000000"}}
sheet.add_row ['1', '2', '3', '4'], style: default_styles
sheet.add_style sheet.rows.last.cells.last.r, other_styles
```

**Comment by westonganger** [comment]
If that fixes it then we can look into augmenting `wb.styles.add_style` to do something similar to [cell.add_style](https://github.com/axlsx-styler-gem/axlsx_styler/blob/35795f5ecfd130c6f949035e4381c93bc29aa9ec/lib/axlsx_styler/axlsx_cell.rb#L7) where we keep track of the styles for re-use later.

**Comment by westonganger** [comment]
Ah seems that Arial is used on this line here. I think this was the default for the sheet. Maybe there is some way better we could be doing this?

https://github.com/axlsx-styler-gem/axlsx_styler/blob/35795f5ecfd130c6f949035e4381c93bc29aa9ec/lib/axlsx_styler/axlsx_styles.rb#L11-L15

Maybe you can post the portion of your code that sets the font as well and how that comes into play here.

**Comment by newfylox** [comment]
Well nothing magic on my side, I only set the default font to my whole sheet by doing this
```ruby
sheet.styles.fonts[0].name = 'Pontiac'
```
and then all my cells have this font. But using `add_style` removes it to Arial.

**Comment by westonganger** [comment]
Ok i didnt know you could do that. Looks like we can use this value where we set Arial. 

Is there any other methods that you are calling other than `font` and `add_style` on `sheet.styles`

**Comment by westonganger** [comment]
Yeah i expected fonts is just a list of all fonts in the spreadsheet. And i guess default behaviour is that the whole spreadsheet uses the first available font when not specifying.

I suspect if we call sheet.styles.fonts(0) before setting it to anything then i think it should be defaulting to Arial (not because of axlsx_styler)

**Comment by newfylox** [comment]
Is it mandatory to set font name? Will it break removing this parameter? If it's working it would preserve user's preferences, therefore not overriding font. Anyways, thanks for sharing thoughts about this!

**Comment by westonganger** [comment]
So seems to me we would still need to find a dynamic way to get `sz: 11, family: 1` too. If you know something here.

**Comment by newfylox** [comment]
> Instead of using `wb.styles.add_style` try just adding your styles directly to `add_row`
> 
> ```ruby
> default_styles = {border: {style: :thin, color: "000000"}}
> sheet.add_row ['1', '2', '3', '4'], style: default_styles
> sheet.add_style sheet.rows.last.cells.last.r, other_styles
> ```
I forgot to tell you that this solution doesn't work, it throws an error `no implicit conversion of Integer into Hash`

```ruby
wb = xlsx_package.workbook
s = wb.styles
border = s.add_style border: { style: :thin, color: "000000" }
...
sheet.add_row ['1', '2', '3', '4'], style: border
...
```
Using my solution above with your new commit on branch `master`, it doesn't work because of this:
https://github.com/axlsx-styler-gem/axlsx_styler/blob/35795f5ecfd130c6f949035e4381c93bc29aa9ec/lib/axlsx_styler/axlsx_styles.rb#L11
`options={}` is getting this as params `{:type=>:xf, :name=>"Arial", :sz=>11, :family=>1, :border=>{:style=>:thin, :color=>"000000"}, :bg_color=>"00b0f0"}`

and options are overriding font_defaults. Probably we should reverse those merge
```ruby
raw_style = {type: :xf}.merge(font_defaults).merge(options) # right now
raw_style = {type: :xf}.merge(options).merge(font_defaults) # probably the solution, or better idea
```

**Comment by westonganger** [comment]
For `no implicit conversion of Integer into Hash` this is another error I was wondering how didnt get triggered. Seemed you failed to mention this. I can make a separate PR to resolve this likely.

```ruby
# Not working
border = s.add_style border: { style: :thin, color: "000000" }
sheet.add_row ['1', '2', '3', '4'], style: border
```

**Comment by westonganger** [comment]
After the changes I made you should be able to do the following

```ruby
sheet.styles.fonts[0].name = 'Pontiac'

sheet.add_row [1,2,3], style: {b: true}
# styles applied should be `{:type=>:xf, :name=>"Pontiac", :sz=>11, :family=>1, :b=>true}`
```

**Comment by westonganger** [comment]
Can you please tell me why your one output has the following

```
{:type=>:xf, :name=>"Arial", :sz=>11, :family=>1, :border=>{:style=>:thin, :color=>"000000"}, :bg_color=>"00b0f0"}
```

I am wondering how the `:bg_color` got there. Maybe you omitted something or can you show how you have assigned `:bg_color`? I am wondering if somehow you defined bg_color globally, same as you did with the default font.

**Comment by newfylox** [comment]
I just forgot to show more code that I did before. I did a couple of `add_styles` adding background color, centered text, etc. But nowhere I'm putting `Arial` font and then my `Pontiac` font got override like my previous comment told.

**Comment by westonganger** [comment]
Ok can you please confirm that if you remove `axlsx_styler` from your project that you can get the code working as you expect.

**Comment by newfylox** [comment]
Well removing `axlsx_styler` works for my font, but I don't think it "reveals" any hints because when doing this, I'm not using `add_style` nor `add_border` and so it's plain `caxlsx` style
