### ISSUE TITLE
ActiveSupport lock

### ISSUE THREAD

**Issue by dalpo** [sakovias/axlsx_styler#17]
With the latest `v0.1.6` version, ActiveSupport is now locked to the `3.x` family versions, which is a problem for people using a any library depending from greater versions of ActiveSupport. 

For instance any version of rails >= 4.x:

```
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 5.0.0.1)

  In Gemfile:
    activemodel-serializers-xml (~> 1.0.0) was resolved to 1.0.0, which depends on
      activesupport (> 5.x)

    rails (~> 5.0.0) was resolved to 5.0.0.1, which depends on
      activejob (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
        globalid (>= 0.3.6) was resolved to 0.3.7, which depends on
          activesupport (>= 4.1.0)

    axlsx_styler (~> 0.1.6) was resolved to 0.1.6, which depends on
      activesupport (~> 3.1)
```

**Comment by sakovias** [comment]
@dalpo thanks for reporting! As a quick fix, I've reverted back to open-ended dependency on `ActiveSupport`. A cleaner fix would be to remove this dependency entirely, but I'll address this in upcoming versions.

Please let me know if there are no issues with v0.1.7.

**Comment by sakovias** [comment]
Just for the reference, the fixing commit https://github.com/sakovias/axlsx_styler/commit/7f968bebc741e8cc5a7d4c85e8a5b8d808426553

**Comment by dalpo** [comment]
@sakovias It works well!
Thanks :)
