### ISSUE TITLE
Update to support axlsx 3.0.0

### ISSUE THREAD

**Issue by davefp** [sakovias/axlsx_styler#19]
There's a 3.0.0 branch of `axlsx` prepping for release here: https://github.com/randym/axlsx/tree/release-3.0.0

`axlsx-styler` is currently locked to 2.x, so won't work with the new version.

This might be as simple as making the dependency open-ended in the gemspec, but I haven't had a close look at all the changes.

**Comment by nfruneau** [comment]
I contacted Sakovias, he doesn't code on ruby anymore but still is open to accept pull requests if needed :)

**Comment by davefp** [comment]
I'll prep a PR, thanks@

**Comment by davefp** [comment]
@nfruneau Ha! I just spotted that you've got a PR open already. :)

**Comment by nicolasfruneau** [comment]
yes I am using my branch atm to overcome the issue and it works well, but if you want to make some  integration tests as @sakovias requested feel free to do so :)

**Comment by sakovias** [comment]
https://github.com/sakovias/axlsx_styler/pull/21
