### ISSUE TITLE
add_border trips up on borders previously set with add_style (ver.: 0.1.3)

### ISSUE THREAD

**Issue by HuBandiT** [sakovias/axlsx_styler#6]
I am trying to draw a table with a thin grid and a medium outline:

this correctly draws the grid:
```
wb.add_worksheet(name: "foo") do |sheet|
  sheet.add_row ['1', '2', '3']
  sheet.add_row ['4', '5', '6']
  sheet.add_row ['7', '8', '9']
  sheet.add_style 'A1:C3', border: {style: :thin, color: '000000'}
end
wb.apply_styles
```

this correctly draws the outline:
```
wb.add_worksheet(name: "foo") do |sheet|
  sheet.add_row ['1', '2', '3']
  sheet.add_row ['4', '5', '6']
  sheet.add_row ['7', '8', '9']
  sheet.add_border 'A1:C3', style: :medium
end
wb.apply_styles
```

but I get an error if I try to combine the two:
```
wb.add_worksheet(name: "foo") do |sheet|
  sheet.add_row ['1', '2', '3']
  sheet.add_row ['4', '5', '6']
  sheet.add_row ['7', '8', '9']
  sheet.add_style 'A1:C3', border: {style: :thin, color: '000000'}
  sheet.add_border 'B2:C3', style: :medium
end
wb.apply_styles
```
```
ActionView::Template::Error (undefined method `+' for nil:NilClass)
```

and I get a different error if I try the other way around:
```
wb.add_worksheet(name: "foo") do |sheet|
  sheet.add_row ['1', '2', '3']
  sheet.add_row ['4', '5', '6']
  sheet.add_row ['7', '8', '9']
  sheet.add_border 'A1:C3', style: :medium
  sheet.add_style 'A1:C3', border: {style: :thin, color: '000000'}
end
wb.apply_styles
```
```
ActionView::Template::Error (no implicit conversion of nil into Array)
```

**Comment by sakovias** [comment]
Thanks for reporting these!

I know where the problem is. The question now is whether we can allow `axlsx` grids
```
sheet.add_style 'A1:C3', border: {style: :thin, color: '000000'}
```
without breaking the existing  DSL
```
sheet.add_border 'A1:C3', {style: :thin, color: '000000'}
```
The latter creates a "frame" around the cells and not a grid.

**Comment by HuBandiT** [comment]
A common task I seem to face is have a grid between all cells in a range, and then "on top of that", I need to mark some rectangular groups of cells with a thicker line, most often the outer borders of the entire range, but also sometimes a header row and a header column.

Best would be if all drawing operations would be cumulative in the sense that the border drawing operation overrides those and only those borders that are part of the current operation, and set those to the style specified. E.g. my third example above: It would draw a grid over the range with thin lines via the add_style call, then draw a thicker outline on the outer border of the specified range during the add_border call.

**Comment by sakovias** [comment]
I'll take a look later this week. I'm not sure if grid is the same as border at least as far as Excel goes. I think `axlsx` does not allow to create borders of different style on different edges of a cell, but a solution could be to use a different style option (if such option exists).

**Comment by sakovias** [comment]
@HuBandiT, could you provide a screenshot of an Excel file you're trying to create? I just want to make sure I'll be solving the right problem.
