### ISSUE TITLE
Support for format_code or num_fmt

### ISSUE THREAD

**Issue by westonganger** [sakovias/axlsx_styler#8]
I was having no success getting a `format_code` or `num_fmt` so that I can get number and currency formats. Is this supported or do you know how we can add it?

This is my code:

    sheet.add_style "B2:E5", format_code: "$#,##0.00"

**Comment by sakovias** [comment]
Please make sure this is something `axlsx` can handle. If it doesn't, this gem won't either.

How do you open your Excel files? I've noticed that apps like LibreOffice may have problems supporting everything MS Excel supports.

**Comment by westonganger** [comment]
I have successfully been using this in my gem SpreadsheetArchitect. It works like this.

```
sheet.add_row row_data, style: package.workbook.styles.add_style({b: true, format_code: "$#,##0.00"}), types: options[:types]
```

However I only know how to apply it to the whole row except for string cells.

Yes, I have been using LibreOffice. But like I say the above works for the formatting for the whole row.

**Comment by sakovias** [comment]
Hmm, I can't reproduce... I need the whole piece of code to see where you problem is.
``` ruby
sheet.add_row ['A1', 'B1', 'C1']
sheet.add_row ['A2', 10002.23, 873984723]
sheet.add_row ['A3', 328982.26, 373570240.82]
sheet.add_row ['A4', 87234972, 980824.1]
sheet.add_style 'B2:C4', format_code: "$#,##0.00"
```
![num-fmt](https://cloud.githubusercontent.com/assets/4750367/15032942/0190973a-1234-11e6-9728-df1eb6e2bbca.png)

**Comment by westonganger** [comment]
Is that in LibreOffice or Excel?

**Comment by sakovias** [comment]
That's in LibreOffice.

**Comment by westonganger** [comment]
The problem here was that I was not calling the method `workbook.apply_styles`. The readme doesn't put any emphasis on having to call this method. I suggest the readme be re-written to include this call in more of the examples

**Comment by sakovias** [comment]
Agreed, some more emphasis should be put on this.
